name: monster_habit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  auto_route: ^6.3.0
  auto_route_generator: ^6.2.0
  percent_indicator: ^4.2.3
  flutter_rating_bar: ^4.0.1
  speech_balloon: ^0.0.4
  hooks_riverpod: ^2.3.8
  riverpod_generator: ^2.3.9
  flutter_svg: ^2.0.9
  supabase_flutter: ^2.3.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  animated_bottom_navigation_bar: ^1.3.3
  simple_logger: ^1.9.0+3
  timezone: ^0.9.2
  intl: ^0.18.1
  flutter_localization: ^0.2.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.4.1
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/stub/
    - images/svg/
